version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/ms-bff"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/ms-cloud-config"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/ms-covid"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/ms-population"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/ms-covid-data-loader"
    schedule:
      interval: "daily"
