version: '3.7'

services:

  jaeger:
    # Jaeger UI: http://localhost:16686/
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=podiyumm
    ports:
      - 27017:27017
    restart: always