version: '3.7'

services:

  jaeger:
    # Jaeger UI: http://localhost:16686/
    image: jaegertracing/all-in-one:1.22
    restart: always
    ports:
      - 5778:5778
      - 9411:9411
      - 16686:16686
      - 14268:14268
      - 14250:14250
    env_file:
      - k8s/jaeger.properties

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - k8s/rabbitmq.properties
    volumes:
      - ./k8s/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./k8s/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  ms-cloud-config:
    image: msshowcase/ms-cloud-config
    restart: always
    ports:
      - "8888:8888"
    env_file:
      - k8s/ms-cloud-config.properties
