version: '3.7'

services:

  jaeger:
    # Jaeger UI: http://localhost:16686/
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - k8s/rabbitmq.properties

  ms-cloud-config:
    image: msshowcase/ms-cloud-config:latest
    restart: always
    ports:
      - "8098:8888"
  #    env_file:
  #      - k8s/ms-cloud-config.properties

  ms-eureka-server:
    image: msshowcase/ms-eureka-server:latest
    restart: always
    ports:
      - "8099:8888"
#    env_file:
#      - k8s/ms-eureka-server.properties