version: '3.7'

services:

  jaeger:
    # Jaeger UI: http://localhost:16686/
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268

  postgres:
    image: postgres:alpine
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ms-population
      POSTGRES_PASSWORD: ms-population
      POSTGRES_DB: ms-population

  adminer:
    image: michalhosna/adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DB: ms-population
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: ms-population
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: ms-population
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: ms-population dedicated Adminer instance

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=podiyumm
    ports:
      - 27017:27017
    restart: always