spec:
  template:
    spec:
      containers:
        - name: {{ DEPLOYMENT_NAME }}
          readinessProbe:
            httpGet:
              path: {{ READINESS_PROBE }}
              port: {{ SVC_PORT }}
            initialDelaySeconds: 1
            periodSeconds: 3