spec:
  template:
    spec:
      containers:
        - name: {{ DEPLOYMENT_NAME }}
          livenessProbe:
            httpGet:
              path: {{ LIVENESS_PROBE }}
              port: {{ SVC_PORT }}
            initialDelaySeconds: 15
            periodSeconds: 30