spec:
  template:
    spec:
      containers:
        - name: {{ DEPLOYMENT_NAME }}
          volumeMounts:
          - name: "rabbitmq-config"
            mountPath: "/etc/rabbitmq/rabbitmq.conf"
            subPath: "rabbitmq.conf"
          - name: "rabbitmq-config"
            mountPath: "/etc/rabbitmq/definitions.json"
            subPath: "definitions.json"
      restartPolicy: Always
      volumes:
        - name: "rabbitmq-config"
          configMap:
            name: "rabbitmq-config"