name: ms-covid-data-loader CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./ms-covid-data-loader

jobs:

  docker:
    name: docker ms-covid-data-loader
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ms-covid-data-loader
          push: true
          tags: msshowcase/ms-covid-data-loader:${{ github.sha }},msshowcase/ms-covid-data-loader:latest