name: ms-bff CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./ms-bff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      # share artifact across jobs
      - name: 'Tar files'
        run: tar -cvf app.tar build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: ms-bff/app.tar

  docker:
    name: docker ms-bff
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      # share artifact across jobs
      - uses: actions/download-artifact@v2
        with:
          name: app
      - name: 'Untar files'
        run: mkdir -p build && tar -xvf ../app.tar build
      # build + push docker img
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./ms-bff
          push: true
          tags: msshowcase/ms-bff:${{ github.sha }},msshowcase/ms-bff:latest